import { describe, expect, it } from 'vitest'
import { toUnocss } from '../src/toUnocss'

describe('tailwind docs coverage', () => {
  const cases = [
    ['break-after:auto;', 'break-after-auto'],
    ['break-before:page;', 'break-before-page'],
    ['break-inside:avoid;', 'break-inside-avoid'],
    ['box-decoration-break:slice;', 'box-decoration-slice'],
    ['box-sizing:content-box;', 'box-content'],
    ['display:inline-block;', 'inline-block'],
    ['display:flex;', 'flex'],
    ['display:grid;', 'grid'],
    ['display:contents;', 'contents'],
    ['float:right;', 'float-right'],
    ['float:inline-end;', 'float-end'],
    ['clear:inline-start;', 'clear-inline-start'],
    ['clear:both;', 'clear-both'],
    ['object-fit:cover;', 'object-cover'],
    ['object-fit:none;', 'object-none'],
    ['object-position:center;', 'object-center'],
    ['object-position:right top;', 'object-right-top'],
    ['overflow:clip;', 'overflow-clip'],
    ['overflow:scroll;', 'overflow-scroll'],
    ['overflow-x:hidden;', 'overflow-x-hidden'],
    ['overflow-y:scroll;', 'overflow-y-scroll'],
    ['overscroll-behavior:contain;', 'overscroll-contain'],
    ['overscroll-behavior:none;', 'overscroll-none'],
    ['overscroll-behavior-y:none;', 'overscroll-y-none'],
    ['overscroll-behavior-x:auto;', 'overscroll-x-auto'],
    ['z-index:auto;', 'z-auto'],
    ['flex-direction:row;', 'flex-row'],
    ['flex-wrap:wrap;', 'flex-wrap'],
    ['flex-wrap:nowrap;', 'flex-nowrap'],
    ['flex:0 1 auto;', 'flex="[0_1_auto]"'],
    ['grid-auto-flow:dense;', 'grid-flow-dense'],
    ['grid-auto-columns:max-content;', 'auto-cols-max'],
    ['grid-auto-rows:max-content;', 'auto-rows-max'],
    ['justify-content:center;', 'justify-center'],
    ['justify-content:stretch;', 'justify-stretch'],
    ['justify-items:end;', 'justify-items-end'],
    ['justify-self:center;', 'justify-self-center'],
    ['align-content:baseline;', 'content-baseline'],
    ['align-items:baseline;', 'items-baseline'],
    ['align-self:auto;', 'self-auto'],
    ['place-content:stretch;', 'place-content-stretch'],
    ['place-items:stretch;', 'place-items-stretch'],
    ['place-self:center;', 'place-self-center'],
    ['background-attachment:scroll;', 'bg-scroll'],
    ['background-attachment:local;', 'bg-local'],
    ['background-clip:content-box;', 'bg-clip-content'],
    ['background-origin:padding-box;', 'bg-origin-padding'],
    ['background-repeat:round;', 'bg-repeat-round'],
    ['background-repeat:space;', 'bg-repeat-space'],
    ['border-style:solid;', 'border-solid'],
    ['border-style:hidden;', 'border-hidden'],
    ['border-collapse: separate;', 'border-separate'],
    ['outline-style:solid;', 'outline-solid'],
    ['outline-style:dotted;', 'outline-dotted'],
    ['outline-width:1px;', 'outline-1px'],
    ['outline-offset:4px;', 'outline-offset-4px'],
    ['mix-blend-mode:multiply;', 'mix-blend-multiply'],
    ['background-blend-mode:multiply;', 'bg-blend-multiply'],
    ['caption-side:bottom;', 'caption-bottom'],
    ['font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif;', 'font-serif'],
    ['font-variant-numeric: slashed-zero;', 'slashed-zero'],
    ['list-style-position:inside;', 'list-inside'],
    ['list-style-type:disc;', 'list-disc'],
    ['list-style-type:decimal;', 'list-decimal'],
    ['text-align:start;', 'text-start'],
    ['text-align:end;', 'text-end'],
    ['text-decoration-style:dashed;', 'decoration-dashed'],
    ['text-decoration-style:dotted;', 'decoration-dotted'],
    ['text-decoration-thickness:auto;', 'decoration-auto'],
    ['text-overflow:clip;', 'text-clip'],
    ['text-transform:lowercase;', 'lowercase'],
    ['text-transform:capitalize;', 'capitalize'],
    ['text-transform:none;', 'normal-case'],
    ['text-wrap:nowrap;', 'text-nowrap'],
    ['text-wrap:balance;', 'text-balance'],
    ['vertical-align:top;', 'v-top'],
    ['vertical-align:middle;', 'v-middle'],
    ['white-space:nowrap;', 'whitespace-nowrap'],
    ['white-space:pre;', 'whitespace-pre'],
    ['white-space:pre-line;', 'whitespace-pre-line'],
    ['white-space:break-spaces;', 'whitespace-break-spaces'],
    ['scroll-snap-align:center;', 'snap-center'],
    ['scroll-snap-align:end;', 'snap-end'],
    ['scroll-snap-stop:always;', 'snap-always'],
    ['scroll-snap-type:y var(--tw-scroll-snap-strictness);', 'snap-y="[var(--tw-scroll-snap-strictness)]"'],
    ['touch-action:manipulation;', 'touch-manipulation'],
    ['touch-action:pan-y;', 'touch-pan-y'],
    ['caret-color:transparent;', 'caret-transparent'],
    ['stroke-width:1;', 'stroke-1'],
  ] as const

  for (const [css, expected] of cases) {
    it(css, () => {
      expect(toUnocss(css)).toBe(expected)
    })
  }
})
